name = "theme-dotty"
routes = [
  { pattern = "dotty.hexly.ai", custom_domain = true }
]
workers_dev = false
preview_urls = false
main = "worker.js"
compatibility_date = "2026-03-08"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = ["/api/live"]
